### ISSUE TITLE
Problema com os Path 

### ISSUE THREAD

**Issue by tmrfo1-iul** [tmrfo1/ES1-2017-EIC2-02#3]
Ao tentar gravar os File Path dos ficheiros com caracteres especiais (acentos,cedilhas,etc) notei que os Path não ficam correctamente guardados. Provavelmente deve estar relacionado com o tipo de encodeamento de texto.

**Comment by afmfe-iul** [comment]
Ficou resolvido neste commit: c7e99625d4b5fff04b23978b8ae3c9cb5cce5ac1
